### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by funnycups** [keengo99/kwebp#2]
编译kwebp：cmake . -DKANGLE_DIR=/vhs/kangle
提示CMake Error in /root/kwebp/build/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Found relative path while evaluating include directories of "cmTC_5a6e9":

    "OFF"

CMake Error in /root/kwebp/build/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Found relative path while evaluating include directories of "cmTC_5a6e9":

    "OFF"

CMake Error at /usr/share/cmake-3.10/Modules/CheckIncludeFiles.cmake:69 (try_compile):  Failed to generate test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:41 (check_include_files)

-- Configuring incomplete, errors occurred!

**Comment by keengo99** [comment]
使用最新版本的kangle，不支持老板本。
